# Generated by Django 4.0.1 on 2022-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='has_perm',
            field=models.BooleanField(default=False, verbose_name='Administrador?'),
        ),
    ]
