# Generated by Django 4.0.1 on 2022-07-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustom_has_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='has_perm',
        ),
    ]
