# Generated by Django 4.0.1 on 2022-07-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usercustom_has_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='has_perm',
            field=models.BooleanField(default=True, verbose_name='Administrador?'),
        ),
    ]
