# Generated by Django 4.0.1 on 2022-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usercustom_has_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/userPhoto'),
        ),
    ]
