# Generated by Django 4.0.1 on 2022-07-13 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usercustom_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
