# Generated by Django 4.0.1 on 2022-07-13 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usercustom_bio_usercustom_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='create_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
