# Generated by Django 4.0.1 on 2022-04-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
