# Generated by Django 4.0.1 on 2022-04-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='SOME STRING', max_length=500),
        ),
    ]
