# Generated by Django 4.0.1 on 2022-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(max_length=500, verbose_name='Ideia Central do Texto'),
        ),
    ]
